version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/workspace

    steps:
      - checkout
      - run: 
          name: creating directories
          command: |
            mkdir test-results
      - run:
          name: install application dependencies
          command: |
            sudo pip install pipenv
            pipenv install

  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: unittesting
          command: |
            mkdir test-results
            pipenv run python -m unittest validate.py
            
      - store_test_results:
          path: test-results/

      - store_artifacts:
          path: test-results/
          destination: tr1
  deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Deploying application
          command: |
            mkdir test-results
            pipenv run python application.py
            
      - store_test_results:
          path: test-results/

      - store_artifacts:
          path: test-results/
          destination: tr1          
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test
      - deploy
